#ifndef RSS_FEED_READER_HEADERS_MAIN_WINDOW_CENTRAL_PART_OF_WINDOW_WITH_GRAPHIC_EFFECT_H_
#define RSS_FEED_READER_HEADERS_MAIN_WINDOW_CENTRAL_PART_OF_WINDOW_WITH_GRAPHIC_EFFECT_H_

#include <QWidget>


class CentralPartOfWindowWithGraphicEffect : public QWidget
{
public:
	explicit CentralPartOfWindowWithGraphicEffect(QWidget *);
};

#endif  // RSS_FEED_READER_HEADERS_MAIN_WINDOW_CENTRAL_PART_OF_WINDOW_WITH_GRAPHIC_EFFECT_H_
